service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.lambda_handler
    timeout: 30  # Set the timeout here
    events:
      - httpApi:
          path: /
          method: get
